/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { InstanceShip__factory } from "./InstanceShip__factory";
export { InstanceShipFourth__factory } from "./InstanceShipFourth__factory";
export { InstanceShipSec__factory } from "./InstanceShipSec__factory";
export { InstanceShipThird__factory } from "./InstanceShipThird__factory";
export { Main__factory } from "./Main__factory";
export { Ship__factory } from "./Ship__factory";
