/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyShip2__factory } from "./MyShip2__factory";
export { MyShipSec__factory } from "./MyShipSec__factory";
