/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InstanceShipSec } from "./InstanceShipSec";
export type { InstanceShipThird } from "./InstanceShipThird";
